"""[Add] Composite Primary Key - PriceData

Revision ID: 53036188f890
Revises: 741e15193330
Create Date: 2025-04-01 20:47:50.756770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53036188f890'
down_revision: Union[str, None] = '741e15193330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_cntry_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key('companies_cntry_fkey', 'companies', 'countries', ['country'], ['name'], ondelete='CASCADE')
    op.drop_constraint('prices_data_ticker_fkey', 'prices_data', type_='foreignkey')
    op.create_foreign_key('pricedata_cmpny_fkey', 'prices_data', 'assets', ['ticker'], ['ticker'], ondelete='CASCADE')
    op.drop_column('prices_data', 'id')
    
    op.create_primary_key(
        "pk_prices_data",
        "prices_data",
        ["date", "ticker", "open_status"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("pk_prices_data", "prices_data", type_="primary")
    
    op.add_column('prices_data', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint('pricedata_cmpny_fkey', 'prices_data', type_='foreignkey')
    op.create_foreign_key('prices_data_ticker_fkey', 'prices_data', 'assets', ['ticker'], ['ticker'])
    op.drop_constraint('companies_cntry_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key('companies_cntry_fkey', 'companies', 'countries', ['country'], ['name'], ondelete='SET NULL')
    # ### end Alembic commands ###
