"""[Add] Cascade Behavior Asset+Company

Revision ID: 63c9dc00c90c
Revises: cfe52013a7b4
Create Date: 2025-03-11 01:09:47.446007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c9dc00c90c'
down_revision: Union[str, None] = 'cfe52013a7b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_ticker_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key('companies_ticker_fkey', 'companies', 'assets', ['ticker'], ['ticker'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('companies_ticker_fkey', 'companies', type_='foreignkey')
    op.create_foreign_key('companies_ticker_fkey', 'companies', 'assets', ['ticker'], ['ticker'])
    # ### end Alembic commands ###
