"""[Add] Country+PriceData+Pair DB

Revision ID: 872d09b34c6d
Revises: f4321da9038c
Create Date: 2025-02-25 22:10:14.560622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '872d09b34c6d'
down_revision: Union[str, None] = 'f4321da9038c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('isin_code', sa.String(length=20), nullable=True),
    sa.Column('bloomberg_code', sa.String(length=20), nullable=True),
    sa.Column('yfinance_code', sa.String(length=20), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('pairs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tickerA', sa.String(), nullable=True),
    sa.Column('tickerB', sa.String(), nullable=True),
    sa.Column('ceof', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['tickerA'], ['assets.ticker'], ),
    sa.ForeignKeyConstraint(['tickerB'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prices_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('open_status', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('shares_outstanding', sa.Float(), nullable=True))
    op.add_column('companies', sa.Column('floating_shares', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'floating_shares')
    op.drop_column('companies', 'shares_outstanding')
    op.drop_table('prices_data')
    op.drop_table('pairs')
    op.drop_table('countries')
    # ### end Alembic commands ###
