"""[Add] Company name column

Revision ID: cfe52013a7b4
Revises: 872d09b34c6d
Create Date: 2025-03-11 00:45:41.487043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe52013a7b4'
down_revision: Union[str, None] = '872d09b34c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###
