"""[Add] Asset+Company tables

Revision ID: f4321da9038c
Revises: 
Create Date: 2025-02-17 00:49:24.039743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4321da9038c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('ticker', sa.String(length=15), nullable=False),
    sa.Column('atype', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('companies',
    sa.Column('ticker', sa.String(length=15), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=20), nullable=True),
    sa.Column('industry', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['assets.ticker'], ),
    sa.PrimaryKeyConstraint('ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies')
    op.drop_table('assets')
    # ### end Alembic commands ###
